# this is to remove size constraints
windowrule = size * *, match:class steam, match:title Steam
windowrule = size * *, match:class steam, match:title Friends List

# remove the center constraint
windowrule = center on, match:class steam, match:title Steam
windowrule = center on, match:class steam, match:title Friends List

windowrule = float off, match:class steam
windowrule = opacity 1 1, match:class steam.*
windowrule = idle_inhibit fullscreen, match:class steam
