# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
#- "/dev/input/by-id/usb-NOVATEK_USB_Keyboard-event-kbd"

# this is executed when mouseless starts, e.g. useful for setting the keyboard layout
# startCommand: "setxkbmap de"

# the rate at which the mouse pointer moves (in ms)
mouseLoopInterval: 20

baseMouseSpeed: 1000.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0 # 200.0 is good
mouseAccelerationCurve: 2.0  # 2.0 is good
startMouseSpeed: 0.0
mouseDecelerationTime: 300.0 # 300.0 is good
mouseDecelerationCurve: 3.0  # 3.0 is good

# enables auto-repeat of a tap key when pressed twice within this duration
quickTapTime: 10
# two keys must be pressed within this duration to activate a combo (e.g. f+d)
comboTime: 0

layers:
- name: initial
  bindings:
    tab: tap-hold-next tab ; toggle-layer mouse ; 750
#    a: tap-hold a ; toggle-layer mouse ; 300
    f+d: layer mouse
- name: mouse
  passThrough: true
  enterCommand: "notify-send 'entered'"
  exitCommand: "notify-send 'exited'"
  bindings:
    esc: layer initial
    q: reload-config
    l: move  1  0
    j: move -1  0
    k: move  0  1
    i: move  0 -1
    leftshift: tap-hold-next leftshift ; toggle-layer pan ; 0
    u: button left
    o: button right
- name: pan
  passThrough: true
  bindings:
    u: button left
    l: right
    j: left
    k: down
    i: up
